import { synergyApi, synergyRu } from '~/utils/mediaCdn';
const video = [
  {
    video: 'https://rutube.ru/play/embed/fe6eb6e1f8142de92159c0b3d4dbea48/?p=NDGiwvTDcr0-AvgO6giDCw',
    image: synergyRu('content/gallery/robototehnika.webp'),
    title: '1 Секреты офлайн и&nbsp;онлайн-маркетинга',
    text: 'Игорь Манн',
    tag: 'Маркетинг',
    category: 'SMM',
  },
  {
    video: 'https://rutube.ru/play/embed/fe6eb6e1f8142de92159c0b3d4dbea48/?p=NDGiwvTDcr0-AvgO6giDCw',
    image: synergyRu('content/gallery/mezhdunarodnyij_festival_komand_kvn_kivin_2025_v_sochi.webp'),
    title: '2 Каким должен быть контент для&nbsp;продвижения товара',
    text: 'Майкл Джанда',
    tag: 'Бизнес',
    category: 'Таргетинг',
  },
  {
    video: 'https://rutube.ru/play/embed/fe6eb6e1f8142de92159c0b3d4dbea48/?p=NDGiwvTDcr0-AvgO6giDCw',
    image: synergyRu('content/gallery/den_otkryityix_dverej_na_tverskoj.webp'),
    title: '3 Как создавать эффективные маркетинговые кампании',
    text: 'Роланд Фрейзер',
    tag: 'Наука и здоровье',
    category: 'Лидогенерация',
  },
  {
    video: 'https://rutube.ru/play/embed/fe6eb6e1f8142de92159c0b3d4dbea48/?p=NDGiwvTDcr0-AvgO6giDCw',
    image: synergyRu('content/gallery/kubok_sinergii_po_miru_tankov.webp'),
    title: '4 Секреты офлайн и&nbsp;онлайн-маркетинга',
    text: 'Игорь Манн',
    tag: 'Маркетинг',
    category: 'SMM',
  },
  {
    video: 'https://rutube.ru/play/embed/fe6eb6e1f8142de92159c0b3d4dbea48/?p=NDGiwvTDcr0-AvgO6giDCw',
    image: synergyRu('content/gallery/den_otkryityix_dverej_fakulteta_dizajna.webp'),
    title: '5 Каким должен быть контент для&nbsp;продвижения товара',
    text: 'Майкл Джанда',
    tag: 'Бизнес',
    category: 'SEO',
  },
  {
    video: 'https://rutube.ru/play/embed/fe6eb6e1f8142de92159c0b3d4dbea48/?p=NDGiwvTDcr0-AvgO6giDCw',
    image: synergyRu('content/gallery/den_otkryityix_dverej_na_tverskoj.webp'),
    title: '6 Как создавать эффективные маркетинговые кампании',
    text: 'Роланд Фрейзер',
    tag: 'Наука и здоровье',
    category: 'Автоматизация',
  },
  {
    video: 'https://rutube.ru/play/embed/fe6eb6e1f8142de92159c0b3d4dbea48/?p=NDGiwvTDcr0-AvgO6giDCw',
    image: synergyRu('content/gallery/robototehnika.webp'),
    title: '7 Секреты офлайн и&nbsp;онлайн-маркетинга',
    text: 'Игорь Манн',
    tag: 'Маркетинг',
    category: 'Маркетплейсы',
  },
  {
    video: 'https://rutube.ru/play/embed/fe6eb6e1f8142de92159c0b3d4dbea48/?p=NDGiwvTDcr0-AvgO6giDCw',
    image: synergyRu('content/gallery/mezhdunarodnyij_festival_komand_kvn_kivin_2025_v_sochi.webp'),
    title: '8 Каким должен быть контент для&nbsp;продвижения товара',
    text: 'Майкл Джанда',
    tag: 'Бизнес',
    category: 'Продвижение',
  },
  {
    video: 'https://rutube.ru/play/embed/fe6eb6e1f8142de92159c0b3d4dbea48/?p=NDGiwvTDcr0-AvgO6giDCw',
    image: synergyRu('content/gallery/kosmicheskie_tehnologii.webp'),
    title: '9 Как создавать эффективные маркетинговые кампании',
    text: 'Роланд Фрейзер',
    tag: 'Наука и здоровье',
    category: 'SMM',
  },
  {
    video: 'https://rutube.ru/play/embed/fe6eb6e1f8142de92159c0b3d4dbea48/?p=NDGiwvTDcr0-AvgO6giDCw',
    image: synergyRu('content/gallery/den_rossijskogo_studenchestva_2024.webp'),
    title: '10 Секреты офлайн и&nbsp;онлайн-маркетинга',
    text: 'Игорь Манн',
    tag: 'Маркетинг',
    category: 'Реклама',
  },
  {
    video: 'https://rutube.ru/play/embed/fe6eb6e1f8142de92159c0b3d4dbea48/?p=NDGiwvTDcr0-AvgO6giDCw',
    image: synergyRu('content/gallery/bespilotnye_tehnologii.webp'),
    title: '11 Каким должен быть контент для&nbsp;продвижения товара',
    text: 'Майкл Джанда',
    tag: 'Бизнес',
    category: 'Реклама',
  },
  {
    video: 'https://rutube.ru/play/embed/fe6eb6e1f8142de92159c0b3d4dbea48/?p=NDGiwvTDcr0-AvgO6giDCw',
    image: synergyRu('content/gallery/kitajskij_novyj_god.webp'),
    title: '12 Как создавать эффективные маркетинговые кампании',
    text: 'Роланд Фрейзер',
    tag: 'Наука и здоровье',
    category: 'Реклама',
  },
  {
    video: 'https://rutube.ru/play/embed/fe6eb6e1f8142de92159c0b3d4dbea48/?p=NDGiwvTDcr0-AvgO6giDCw',
    image: synergyRu('content/gallery/otpravlenie_volonterov_na_vsemirnyj_festival_molodezhi_2024.webp'),
    title: '13 Секреты офлайн и&nbsp;онлайн-маркетинга',
    text: 'Игорь Манн',
    tag: 'Маркетинг',
    category: 'SMM',
  },
  {
    video: 'https://rutube.ru/play/embed/fe6eb6e1f8142de92159c0b3d4dbea48/?p=NDGiwvTDcr0-AvgO6giDCw',
    image: synergyRu('content/gallery/nagrazhdenie_volonterov_vsemirnogo_festivalja_molodezhi_2024.webp'),
    title: '14 Каким должен быть контент для&nbsp;продвижения товара',
    text: 'Майкл Джанда',
    tag: 'Бизнес',
    category: 'Таргетинг',
  },
  {
    video: 'https://rutube.ru/play/embed/fe6eb6e1f8142de92159c0b3d4dbea48/?p=NDGiwvTDcr0-AvgO6giDCw',
    image: synergyRu('content/gallery/synergy_friends_welcome_party_2023.webp'),
    title: '15 Как создавать эффективные маркетинговые кампании',
    text: 'Роланд Фрейзер',
    tag: 'Наука и здоровье',
    category: 'Лидогенерация',
  },
  {
    video: 'https://rutube.ru/play/embed/fe6eb6e1f8142de92159c0b3d4dbea48/?p=NDGiwvTDcr0-AvgO6giDCw',
    image: synergyRu('content/gallery/kosmicheskie_tehnologii.webp'),
    title: '16 Как создавать эффективные маркетинговые кампании',
    text: 'Роланд Фрейзер',
    tag: 'Наука и здоровье',
    category: 'Продвижение',
  },
];

export {
  video,
};

