export const ARTICLES = [
  {
    tag: 'Карьера',
    href: 'https://example.com/akademiya/karera/garderob_uspeshnogo_cheloveka_kak_odevatsya_chtobyi_prodvinutsya_po_karernoj_lestnicze',
    date: '03 июля 2025',
    title: 'Гардероб успешного человека: как одеваться, чтобы продвинуться по&nbsp;карьерной лестнице',
    img: 'https://example.com/assets/components/phpthumbof/cache/photo_2025_07_03_15.23.32.7888c54bc46e55b791da50c5285a2284.webP',
  },
  {
    tag: 'Карьера',
    href: 'https://example.com/akademiya/karera/chto_nadet_na_sobesedovanie_chtobyi_vas_zapomnili_i_priglasili_na_rabotu',
    date: '03 июля 2025',
    title: 'Что надеть на&nbsp;собеседование, чтобы вас запомнили и&nbsp;пригласили на&nbsp;работу',
    img: 'https://example.com/assets/components/phpthumbof/cache/photo_2025_07_03_13.10.10.7888c54bc46e55b791da50c5285a2284.webP',
  },
  {
    tag: 'Карьера',
    href: 'https://example.com/akademiya/karera/chek_list_10_sposobov_stat_svoim_na_novoj_rabote',
    date: '29 июля 2025',
    title: '<nobr>Чек-лист:</nobr> 10 способов стать своим на&nbsp;новой работе',
    img: 'https://example.com/assets/components/phpthumbof/cache/188.7888c54bc46e55b791da50c5285a2284.webP',
  },
  {
    tag: 'Карьера',
    href: 'https://example.com/akademiya/karera/kak_prodat_svoi_slabosti_rabotodatelyu',
    date: '28 июля 2025',
    title: 'Как продать свои слабости работодателю: искусство открытости и&nbsp;самопрезентации',
    img: 'https://example.com/assets/components/phpthumbof/cache/120.7888c54bc46e55b791da50c5285a2284.webP',
  },
  {
    tag: 'Карьера',
    href: 'https://example.com/akademiya/karera/kakimi_sovremennyimi_texnologiyami_stoit_ovladet_chtobyi_povyisit_svoyu_czennost_kak_sotrudnika',
    date: '29 июля 2025',
    title: 'Какими современными технологиями стоит овладеть, чтобы повысить свою ценность как сотрудника',
    img: 'https://example.com/assets/components/phpthumbof/cache/127.7888c54bc46e55b791da50c5285a2284.webP',
  },
  {
    tag: 'Карьера',
    href: 'https://example.com/akademiya/karera/5_voprosov_o_rabote_i_karere_kotoryie_stoit_zadat_sebe',
    date: '30 июля 2025',
    title: '5 вопросов о&nbsp;работе и&nbsp;карьере, которые стоит задать&nbsp;себе',
    img: 'https://example.com/assets/components/phpthumbof/cache/akad342.7888c54bc46e55b791da50c5285a2284.webP',
  },
  {
    tag: 'Карьера',
    href: 'https://example.com/akademiya/karera/kak_zavesti_poleznyie_znakomstva_dlya_kareryi',
    date: '30 июля 2025',
    title: 'Как завести полезные знакомства для&nbsp;карьеры',
    img: 'https://example.com/assets/components/phpthumbof/cache/288.7888c54bc46e55b791da50c5285a2284.webP',
  },
  {
    tag: 'Карьера',
    href: 'https://example.com/akademiya/karera/kakie_myagkie_navyiki_vazhno_kachat_dlya_uspeshnoj_kareryi',
    date: '01 августа 2025',
    title: 'Какие мягкие навыки важно качать для&nbsp;успешной карьеры',
    img: 'https://example.com/assets/components/phpthumbof/cache/188.7888c54bc46e55b791da50c5285a2284.webP',
  },
  {
    tag: 'Карьера',
    href: 'https://example.com/akademiya/karera/proxodim_videosobesedovanie_kak_profi_4_poleznyix_soveta',
    date: '01 августа 2025',
    title: 'Проходим видео собеседование как профи: 4 полезных совета',
    img: 'https://example.com/assets/components/phpthumbof/cache/tz_163._kak_upravlyat_udalennoj_komandoj.7888c54bc46e55b791da50c5285a2284.webP',
  },
  {
    tag: 'Карьера',
    href: 'https://example.com/akademiya/karera/5_myagkix_navyikov_dlya_karernogo_rosta',
    date: '01 августа 2025',
    title: '5&nbsp;мягких навыков для&nbsp;карьерного роста',
    img: 'https://example.com/assets/components/phpthumbof/cache/timbilding_montazhnaya_oblast_1.7888c54bc46e55b791da50c5285a2284.webP',
  },
  {
    tag: 'Карьера',
    href: 'https://example.com/akademiya/karera/iskusstvo_povtornogo_otklika_na_vakansiyu',
    date: '17 июня 2025',
    title: 'Искусство повторного отклика на&nbsp;вакансию',
    img: 'https://example.com/assets/components/phpthumbof/cache/gph.7888c54bc46e55b791da50c5285a2284.webP',
  },
  {
    tag: 'Карьера',
    href: 'https://example.com/akademiya/karera/chto_takoe_yarmarka_vakansij_i_kak_v_nej_pouchastvovat',
    date: '17 июня 2025',
    title: 'Что такое ярмарка вакансий и&nbsp;как в&nbsp;ней поучаствовать',
    img: 'https://example.com/assets/components/phpthumbof/cache/inbound_marketing_montazhnaya_oblast_1.7888c54bc46e55b791da50c5285a2284.webP',
  },
  {
    tag: 'Карьера',
    href: 'https://example.com/akademiya/karera/kak_zavesti_poleznyie_znakomstva_esli_vyi_introvert',
    date: '17 июня 2025',
    title: 'Как завести полезные знакомства, если вы интроверт',
    img: 'https://example.com/assets/components/phpthumbof/cache/106._ugc.7888c54bc46e55b791da50c5285a2284.webP',
  },
  {
    tag: 'Карьера',
    href: 'https://example.com/akademiya/karera/kultura_delovogo_obshheniya_chto_takoe_delovoj_etiket_i_kak_ego_soblyudat',
    date: '04 августа 2025',
    title: 'Культура делового общения: что такое деловой этикет и&nbsp;как его соблюдать',
    img: 'https://example.com/assets/components/phpthumbof/cache/355.7888c54bc46e55b791da50c5285a2284.webP',
  },
  {
    tag: 'Карьера',
    href: 'https://example.com/akademiya/karera/oshibki_v_rezyume_prichin_pochemu_vyi_ne_poluchaete_zavetnyij_offer',
    date: '03 сентября 2024',
    title: 'Ошибки в&nbsp;резюме: 12 причин, почему вы не&nbsp;получаете заветный оффер',
    img: 'https://example.com/assets/components/phpthumbof/cache/whatsapp_image_2024_07_01_at_09.19.35.7888c54bc46e55b791da50c5285a2284.webP',
  },
  {
    tag: 'Карьера',
    href: 'https://example.com/akademiya/karera/kak_pravilno_sostavit_rezyume_sekretyi_dlya_privlecheniya_rabotodatelej_i_uspeshnyie_primeryi',
    date: '17 июня 2024',
    title: 'Как правильно составить резюме: секреты для&nbsp;привлечения работодателей и&nbsp;успешные примеры',
    img: 'https://example.com/assets/components/phpthumbof/cache/86_rezzhzld.7888c54bc46e55b791da50c5285a2284.webP',
  },
];
