import { ROUTES } from '~/constants';
import { synergyApi } from '~/utils/mediaCdn';

export const raitings = [
  {
    name: 'по&nbsp;трудоустроенным выпускникам среди вузов России',
    subname: '',
    organization: 'Федеральная служба по&nbsp;труду и&nbsp;занятости',
    logo: synergyApi('uploads/content/ratings/cards/logo/rostrud.webp'),
    year: '2024',
    position: 1,
    difference: '+',
    image: synergyApi('uploads/content/ratings/cards/img/bag.webp'),
    articleLink: 'https://trudvsem.ru/ratings_education_organizations/universities',
  },
  {
    name: 'по&nbsp;уровню средних зарплат выпускников среди вузов России',
    subname: '',
    organization: 'Федеральная служба по&nbsp;труду и&nbsp;занятости',
    logo: synergyApi('uploads/content/ratings/cards/logo/rostrud.webp'),
    year: '2024',
    position: 'ТОП-3',
    difference: '+',
    image: synergyApi('uploads/content/ratings/cards/img/up.webp'),
    articleLink: 'https://trudvsem.ru/ratings_education_organizations/universities',
  },
  {
    name: 'по&nbsp;востребованности выпускников на&nbsp;рынке труда среди вузов России',
    subname: '',
    organization: 'HeadHunter',
    logo: synergyApi('uploads/content/ratings/cards/logo/hh.webp'),
    year: '2024',
    position: 'ТОП-3',
    difference: '+',
    image: synergyApi('uploads/content/ratings/cards/img/man.webp'),
    articleLink: 'https://hh.ru/rating',
  },
  {
    name: 'в&nbsp;рейтинге крупнейших <nobr>EdTech-компаний</nobr>',
    subname: '',
    organization: 'Smart Ranking',
    logo: synergyApi('uploads/content/ratings/cards/logo/ed-techs.webp'),
    year: '2024',
    position: 1,
    difference: '+',
    image: synergyApi('uploads/content/ratings/cards/img/stars.webp'),
    articleLink: 'https://edtechs.ru/',
  },
  {
    name: 'в рейтинге лучших вузов России',
    subname: '',
    organization: 'HeadHunter',
    logo: synergyApi('uploads/content/ratings/cards/logo/hh.webp'),
    year: '2023',
    position: 'ТОП-3',
    difference: '+',
    image: synergyApi('uploads/content/ratings/cards/img/star.webp'),
    articleLink: 'https://hh.ru/article/31475',
  },
  {
    name: 'по количеству студентов',
    subname: '',
    organization: 'Минобрнауки&nbsp;РФ',
    logo: synergyApi('uploads/content/ratings/cards/logo/min-science.webp'),
    year: '2023',
    position: 1,
    difference: '+',
    image: synergyApi('uploads/content/ratings/cards/img/study.webp'),
    articleLink: 'https://example.com/demo-ratings-article',
  },
  {
    name: 'по количеству выпускников',
    subname: '',
    organization: 'Федеральная служба по&nbsp;труду и&nbsp;занятости',
    logo: synergyApi('uploads/content/ratings/cards/logo/rostrud.webp'),
    year: '2024',
    position: 1,
    difference: '+',
    image: synergyApi('uploads/content/ratings/cards/img/study2.webp'),
    articleLink: 'https://trudvsem.ru/ratings_education_organizations/universities',
  },
  {
    name: 'по количеству иностранных студентов',
    subname: '',
    organization: 'Минобрнауки&nbsp;РФ',
    logo: synergyApi('uploads/content/ratings/cards/logo/min-science.webp'),
    year: '2023',
    position: 1,
    difference: '+',
    image: synergyApi('uploads/content/ratings/cards/img/world.webp'),
    articleLink: 'https://minobrnauki.gov.ru/press-center/news/mezhdunarodnoe-sotrudnichestvo/46158/',
  },
  {
    name: 'в&nbsp;рейтинге предпринимательских программ',
    subname: '',
    organization: '«Интерфакс»',
    logo: synergyApi('uploads/content/ratings/cards/logo/interfax.webp'),
    year: '2021',
    position: 1,
    difference: '+',
    image: synergyApi('uploads/content/ratings/cards/img/man2.webp'),
    articleLink: 'https://www.interfax-russia.ru/academia/news/interfaks-provel-ocenku-obrazovatelnyh-programm-rossiyskih-vuzov-po-predprinimatelstvu',
  },
  {
    name: 'Премия «Я&nbsp;знаю:&nbsp;EdTech»',
    subname: '',
    organization: 'Медиагруппа «Комсомольская правда»',
    logo: synergyApi('uploads/content/ratings/cards/logo/kp.webp'),
    year: '2025',
    position: 1,
    difference: '+',
    image: synergyApi('uploads/content/ratings/cards/img/kubok.webp'),
    articleLink: 'https://www.kp.ru/daily/27668/5057233/',
  },
  {
    name: 'по&nbsp;эффективности коммуникаций среди вузов&nbsp;РФ',
    subname: '',
    organization: 'Медиагруппа «Россия сегодня» и&nbsp;Brand Analytics',
    logo: synergyApi('uploads/content/ratings/cards/logo/brand_analitics.webp'),
    year: '2024',
    position: 1,
    difference: '+',
    image: synergyApi('uploads/content/ratings/cards/img/micro.webp'),
    articleLink: 'https://brandanalytics.ru/university-rankings/integral/2024/',
  },
  {
    name: 'Национальный рейтинг университетов',
    subname: '',
    organization: '«Интерфакс»',
    logo: synergyApi('uploads/content/ratings/cards/logo/interfax.webp'),
    year: '2023',
    position: 'ТОП-100',
    difference: '+',
    image: synergyApi('uploads/content/ratings/cards/img/up2.webp'),
    articleLink: 'https://www.interfax-russia.ru/academia/ratings?rating=1&year=2023&page=1',
  },
  {
    name: 'Рейтинг<br>Top Universities in Russia',
    subname: '',
    organization: 'UniRank',
    logo: synergyApi('uploads/content/ratings/cards/logo/uni-rank.webp'),
    year: '2021',
    position: 'ТОП-100',
    difference: '+',
    image: synergyApi('uploads/content/ratings/cards/img/house.webp'),
    articleLink: 'https://www.unirank.org/ru/ranking/',
  },
  {
    name: 'Международный рейтинг вузов',
    subname: '',
    organization: 'QS EECA University Rankings',
    logo: synergyApi('uploads/content/ratings/cards/logo/qs.webp'),
    year: '2021',
    position: 'ТОП-400',
    difference: '+',
    image: synergyApi('uploads/content/ratings/cards/img/world2.webp'),
    articleLink: 'https://www.topuniversities.com/university-rankings/eeca-rankings/2021',
  },
];
