export const mtiMapData = [
  {
    id: 1,
    address: 'Москва, Ленинградский проспект, 80Г',
    country: 'Россия',
    director: '',
    district: 0,
    email: 'demo.mti@university.example',
    filial_name: '',
    iscapital: true,
    isfilial: false,
    key: 1,
    latitude: 55.811159,
    longitude: 37.509999,
    name: 'МТИ',
    phone: '',
    phone_main: '',
    published: true,
    rank: 10000,
    region: 'Россия',
    schedule: 'Пн-Пт: 10:00-17:00',
    slug: 'msc',
    value: 'Москва',
    station: 'Сокол',
  },
];
